import type { CricketCardStats } from "./cricketStats";

// Static, hand-picked examples for the homepage hero. Real GitHub logins + avatars (this is
// exactly the intended use of the tool — showing a few well-known devs to seed interest),
// but the stat numbers here are illustrative placeholders, not live-fetched.
export const SHOWCASE_CARDS: CricketCardStats[] = [
  {
    login: "torvalds",
    name: "Linus Torvalds",
    platform: "github",
    avatarUrl: "https://github.com/torvalds.png",
    role: "Batsman",
    tier: "Legend",
    rating: 96,
    strikeRate: 210,
    battingAverage: 92,
    wickets: 48,
    economy: 2.1,
    boundaries: 251000,
    catches: 38,
    cardStats: [
      { label: "Strike rate", abbr: "STR", value: 82 },
      { label: "Batting avg", abbr: "AVG", value: 92 },
      { label: "Wickets", abbr: "WKT", value: 58 },
      { label: "Economy", abbr: "ECO", value: 95 },
      { label: "Boundaries", abbr: "BND", value: 99 },
      { label: "Catches", abbr: "CAT", value: 77 },
    ],
    scoutingMetrics: [],
    attributes: [],
    playstyles: ["Franchise Player", "Marathoner"],
    accountAgeYears: 16,
    activeYears: 16,
    signatureStat: "Big-hitting star",
  },
  {
    login: "gaearon",
    name: "Dan Abramov",
    platform: "github",
    avatarUrl: "https://github.com/gaearon.png",
    role: "All-rounder",
    tier: "Gold",
    rating: 87,
    strikeRate: 140,
    battingAverage: 78,
    wickets: 36,
    economy: 3.4,
    boundaries: 88000,
    catches: 61,
    cardStats: [
      { label: "Strike rate", abbr: "STR", value: 74 },
      { label: "Batting avg", abbr: "AVG", value: 78 },
      { label: "Wickets", abbr: "WKT", value: 81 },
      { label: "Economy", abbr: "ECO", value: 84 },
      { label: "Boundaries", abbr: "BND", value: 90 },
      { label: "Catches", abbr: "CAT", value: 88 },
    ],
    scoutingMetrics: [],
    attributes: [],
    playstyles: ["Safe Hands", "Century Maker"],
    accountAgeYears: 12,
    activeYears: 12,
    signatureStat: "Safe pair of hands",
  },
  {
    login: "you",
    name: "Your name here",
    platform: "github",
    avatarUrl:
      "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzJGNkIzQyIvPjx0ZXh0IHg9IjEwMCIgeT0iMTE4IiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSI2NCIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iI0Y0RjFFOCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+WU9VPC90ZXh0Pjwvc3ZnPg==",
    role: "Bowler",
    tier: "Bronze",
    rating: 62,
    strikeRate: 60,
    battingAverage: 40,
    wickets: 12,
    economy: 6.5,
    boundaries: 40,
    catches: 6,
    cardStats: [
      { label: "Strike rate", abbr: "STR", value: 44 },
      { label: "Batting avg", abbr: "AVG", value: 40 },
      { label: "Wickets", abbr: "WKT", value: 38 },
      { label: "Economy", abbr: "ECO", value: 52 },
      { label: "Boundaries", abbr: "BND", value: 35 },
      { label: "Catches", abbr: "CAT", value: 28 },
    ],
    scoutingMetrics: [],
    attributes: [],
    playstyles: ["Rising Talent"],
    accountAgeYears: 1.5,
    activeYears: 1,
    signatureStat: "Still finding their game",
  },
  {
    login: "neetcode",
    name: "NeetCode",
    platform: "leetcode",
    avatarUrl:
      "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI0UyODUyQiIvPjx0ZXh0IHg9IjEwMCIgeT0iMTE4IiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSI2NCIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iI0Y0RjFFOCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+TkM8L3RleHQ+PC9zdmc+",
    role: "Bowler",
    tier: "Legend",
    rating: 94,
    strikeRate: 180,
    battingAverage: 88,
    wickets: 320,
    economy: 2.4,
    boundaries: 540,
    catches: 42,
    cardStats: [
      { label: "Strike rate", abbr: "STR", value: 80 },
      { label: "Batting avg", abbr: "AVG", value: 88 },
      { label: "Wickets", abbr: "WKT", value: 96 },
      { label: "Economy", abbr: "ECO", value: 91 },
      { label: "Boundaries", abbr: "BND", value: 93 },
      { label: "Catches", abbr: "CAT", value: 85 },
    ],
    scoutingMetrics: [],
    attributes: [],
    playstyles: ["Death Bowler", "Marathoner"],
    accountAgeYears: 6,
    activeYears: 6,
    signatureStat: "Wicket-taking menace",
  },
];
